[package]
name = "quick-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glam = "0.24.1"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
